version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing Python dependencies..."
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo "Running unit tests..."
      - pytest
  build:
    commands:
      - echo "Building the Python application."
      - echo "Application ready for deployment."
artifacts:
  files:
    - '**/*'
  base-directory: 'host'
